package org.biodiful.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChallengerPoolAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengerPoolAllPropertiesEquals(ChallengerPool expected, ChallengerPool actual) {
        assertChallengerPoolAutoGeneratedPropertiesEquals(expected, actual);
        assertChallengerPoolAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengerPoolAllUpdatablePropertiesEquals(ChallengerPool expected, ChallengerPool actual) {
        assertChallengerPoolUpdatableFieldsEquals(expected, actual);
        assertChallengerPoolUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengerPoolAutoGeneratedPropertiesEquals(ChallengerPool expected, ChallengerPool actual) {
        assertThat(actual)
            .as("Verify ChallengerPool auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengerPoolUpdatableFieldsEquals(ChallengerPool expected, ChallengerPool actual) {
        assertThat(actual)
            .as("Verify ChallengerPool relevant properties")
            .satisfies(a -> assertThat(a.getPoolOrder()).as("check poolOrder").isEqualTo(expected.getPoolOrder()))
            .satisfies(a -> assertThat(a.getChallengersURL()).as("check challengersURL").isEqualTo(expected.getChallengersURL()))
            .satisfies(a -> assertThat(a.getNumberOfMatches()).as("check numberOfMatches").isEqualTo(expected.getNumberOfMatches()))
            .satisfies(a -> assertThat(a.getMatchesDescription()).as("check matchesDescription").isEqualTo(expected.getMatchesDescription())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengerPoolUpdatableRelationshipsEquals(ChallengerPool expected, ChallengerPool actual) {
        assertThat(actual)
            .as("Verify ChallengerPool relationships")
            .satisfies(a -> assertThat(a.getSurvey()).as("check survey").isEqualTo(expected.getSurvey()));
    }
}
